#!/bin/sh

# Use neovim for vim if present.
#[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
  alias $command="sudo $command"
done; unset command

# ytfzf
alias ytfzf="ytfzf -D"
alias dfromhist='yt "$(ytfzf -H -L)"'

fo() {
  cd "$(dirname "$(find | sed -e 's-^./--g' -e 's-^\.*$--g' | fzf)" )"
}

duck () {
  lynx -cfg="~/.config/lynx/lynx.cfg" -lss="~/.config/lynx/lynx.lss" "https://duckduckgo.com/lite/?q=$*"
}
google () {
  lynx -cfg="~/.config/lynx/lynx.cfg" -lss="~/.config/lynx/lynx.lss" "https://www.google.com/search?hl=en&q=$*"
}

alias dotfiles="/usr/bin/git --git-dir=${HOME}/.local/repos/dotfiles --work-tree=$HOME"
alias to="source ~/.local/bin/mine/to"
alias scim="sc-im"
alias mpvg="mpv --player-operation-mode=pseudo-gui"
alias mpvm="mpv --vo=null --video=no --no-video --term-osd-bar"
alias lynx='lynx -cfg="~/.config/lynx/lynx.cfg" -lss="~/.config/lynx/lynx.lss"'
alias \?="duck"
alias \?\?="google"

# Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  mkd="mkdir -pv" \
  yt="youtube-dl --format 'bestvideo[height=?720][vcodec!=?vp9]+bestaudio/best' --add-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  trem="transmission-remote" \
  YT="youtube-viewer" \
  sdn="sudo shutdown -h now" \
  e="/usr/bin/vim" \
  v="$EDITOR" \
  p="pacman" \
  xi="sudo xbps-install" \
  xr="sudo xbps-remove -R" \
  xq="xbps-query" \
  z="zathura"

alias \
  magit="nvim -c MagitOnly" \
  ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
  weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
