##!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

#if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
#	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
#else
#	. "$HOME/.xprofile"
#fi

#( sleep 2 ; sh ${XDG_CONFIG_HOME}/screenlayout/i3) &
# xrdb ${XDG_CONFIG_HOME}/x11/xresources &
# xcompmgr &
# remaps &

#ssh-agent dwm

## ignored --
#exec stumpwm
# xwallpaper --zoom ~/Pictures/walls/cool_sky.jpg &
#exec dbus-launch --exit-with-session emacs -mm --debug-init #-l ~/.doom.d/efs/desktop.el -l ~/.doom.d/efs/init.el

exec i3
